### ISSUE TITLE
Loucass' new rule

### ISSUE THREAD

**Issue by TheElectronWill** [Popcorn-moe/Popcorn.moe-Discord#3]
I respect the rules, that's why I report this issue. :smiley_cat: 
Today, at 18h03, @loucass003 said:

> j'ai dit si y'en as un qui fait une faute et qu'un autre s'en plein il fait une issue

Actually, **as** should be **a** and **plein** should be **plaint**. Also the first letter of the sentence should be capitalized, and the sentence should end with a period.

**Comment by loucass003** [comment]
Perfect ! It will be corrected in a day

**Comment by loucass003** [comment]
Btw, make an issue is not obligatory. Make it only if you care about orthography.

**Comment by TheElectronWill** [comment]
I do care :D
